### ISSUE TITLE
How much gpu memory to inference?

### ISSUE THREAD

**Issue by cschy** [allenai/dream#2]
When I use Tesla V100 32GB to inference, it occurs OOM. And could you tell me how to solve it if I just use [QUERY] consequence? Any help would be appreciated.

**Comment by yulinggu-cs** [comment]
Thanks for reaching out! I was able to run the model successfully by using 2 NVIDIA RTX A6000 GPUs, and the experiment used 121.7GB memory. I’d recommend trying with more than 1 GPU and also lowering the inference time batch size if the issue persists.
